language: bash

# Use Trusty on Linux
sudo: required
dist: trusty

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - squashfs-tools


before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update;
        brew install squashfs;
      fi
    - mksquashfs -version

script:
    - ./run_tests.sh

