#!/bin/sh

#
# Create a squashfs, run it through a merge with an empty directory
# and check that it survives.
#

cat >$INPUT_SQUASHFS_PSEUDOFILE <<EOF
test_dir d 755 root root
test_dir/test_file f 444 root root echo "hello"
EOF

cat >$EXPECTED <<EOF
drwxr-xr-x root/root 32 squashfs-root/test_dir
-r--r--r-- root/root 6 squashfs-root/test_dir/test_file
EOF
