#!/bin/sh

#
# Create a squashfs, run it through a merge with an empty directory
# and check that it survives.
#

ln -s /someplace "$INPUT_SQUASHFS_ROOT/symlink"

cat >$EXPECTED <<EOF
lrwxrwxrwx luser/lgroup 10 squashfs-root/symlink -> /someplace
EOF
